# Debian・Ubuntu向け設定
- block:
  - name: Gitlab Runner repository setting  Debian Ubuntu
    shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"

# CentOS向け設定
- block:
  - name: Gitlab Runner repository setting RH CentOS
    shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

- name: Gitlab Runner install
  package:
    name: gitlab-runner
    state: present
  notify:
    - enable gitlab-runner
    - restart gitlab-runner
